name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, workflow]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - run: npm run test
      - run: npm run test:e2e
